version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      security-updates:
        patterns:
          - "*" # Agrupa todas as atualizações de segurança em um único PR
